### ISSUE TITLE
Visualization with erdantic: UnknownModelTypeError

### ISSUE THREAD

**Issue by fleimgruber** [Health-RI/SeMPyRO#38]
As a user, I wanted to visualize the `DCATDataSet` that is created [here](https://github.com/Health-RI/SeMPyRO/blob/main/docs/Intro.md#extending-with-catalog) with the visualization code taken from [here](https://github.com/Health-RI/SeMPyRO/blob/main/docs/Defining_extendind_a_model.md#visualization-with-erdantic):
```python
import erdantic as erd

erd.draw(dataset, out="dataset.png")
```
which fails with:
```
Traceback (most recent call last):
  File "c:\Users\user\dev\prj\.venv\Lib\site-packages\erdantic\convenience.py", line 143, in draw
    diagram = create(
              ^^^^^^^
  File "c:\Users\user\dev\prj\.venv\Lib\site-packages\erdantic\convenience.py", line 67, in create
    diagram.add_model(mm)
  File "c:\Users\user\dev\prj\.venv\Lib\site-packages\erdantic\core.py", line 575, in add_model
    raise UnknownModelTypeError(model=model, available_plugins=list_plugins())
erdantic.exceptions.UnknownModelTypeError: Given model does not match any supported types. Available plugins: ['pydantic', 'pydantic_v1', 'dataclasses']. Model MRO: access_rights=None conforms_to=None co
```
I looked into the sources and found the inheritance graph: DCATCatalog > DCATDataset > DCATResource > RDFModel > BaseModel. So I expected it to be a pydantic model.

**Comment by agjharms** [comment]
Hi fleimgruber, 

My apologies for the delayed response. I have looked into your issue with erdantic. The implemented functionality only supports drawing diagrams of the class definitions themselves, but unfortunately not of specific instances. This would mean that the following code snippet would work:
```
from sempyro.dcat import DCATCatalog, DCATDataset
erd.draw(DCATCatalog, out="catalog.png")
erd.draw(DCATDataset, out="dataset.png")
```
Currently we do not have plans to implement the functionality of drawing instances with erdantic, but we welcome any PRs.

**Comment by fleimgruber** [comment]
Hi @agjharms,

now it's my turn to apologize for the late response :)

Thanks for checking back, confirming my suspicion and mentioning your plans.

Related: https://github.com/RDFLib/rdflib/issues/3271 and might be the 3rd party solution here as well?

*edit*: The broader issue for reference: https://github.com/RDFLib/rdflib/issues/3165
